//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace netmvc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NetMVCEntities : DbContext
    {
        public NetMVCEntities()
            : base("name=NetMVCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblM_Ruangan> tblM_Ruangan { get; set; }
        public virtual DbSet<tblM_Status> tblM_Status { get; set; }
        public virtual DbSet<tblT_Reservasi> tblT_Reservasi { get; set; }
        public virtual DbSet<Vw_Reservasi> Vw_Reservasi { get; set; }
    
        public virtual int tblM_Ruangan_UpdateToBooked(Nullable<int> pk_id)
        {
            var pk_idParameter = pk_id.HasValue ?
                new ObjectParameter("pk_id", pk_id) :
                new ObjectParameter("pk_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("tblM_Ruangan_UpdateToBooked", pk_idParameter);
        }
    }
}
